#1: correct postrm (file depency & format)

diff --git a/rntoolbox/DEBIAN/postrm b/rntoolbox/DEBIAN/postrm
--- a/rntoolbox/DEBIAN/postrm
+++ b/rntoolbox/DEBIAN/postrm
@@ -3,34 +3,38 @@
 
 APPDIR=/apps/toolbox
 APPNAME=toolbox
-. $APPDIR/scripts/utils.sh
+LOGFILE=/var/log/rntoolbox
+_log() {
+	msg="$(date +'%Y/%m/%d %H:%M:%S') [$APPNAME] $*"
+	echo "$msg" >> ${LOGFILE}
+}
 
 # summary of how this script can be called:
-#        * <postrm> `remove'
-#        * <postrm> `purge'
-#        * <old-postrm> `upgrade' <new-version>
-#        * <new-postrm> `failed-upgrade' <old-version>
-#        * <new-postrm> `abort-install'
-#        * <new-postrm> `abort-install' <old-version>
-#        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
+#		* <postrm> `remove'
+#		* <postrm> `purge'
+#		* <old-postrm> `upgrade' <new-version>
+#		* <new-postrm> `failed-upgrade' <old-version>
+#		* <new-postrm> `abort-install'
+#		* <new-postrm> `abort-install' <old-version>
+#		* <new-postrm> `abort-upgrade' <old-version>
+#		* <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
 # for details, see /usr/share/doc/packaging-manual/
 
 _log "Postrm called with the following arguments: $@"
 
 case "$1" in
-    purge)
-       rm -rf /apps/toolbox
-       systemctl restart apache2.service
-       event_push app readynasd '<delete-s resource-type="LocalApp" resource-id="LocalApp"><LocalApp appname="$APPNAME" success="1"></delete-s>' 0 0
-    ;;
+	purge)
+		rm -rf $APPDIR
+		systemctl restart apache2.service
+		event_push app readynasd '<delete-s resource-type="LocalApp" resource-id="LocalApp"><LocalApp appname="$APPNAME" success="1"></delete-s>' 0 0
+		;;
 
-    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
 	;;
 
-    *)
-        _log "postrm called with unknown argument '$1'"
-        exit 1
+	*)
+		_log "postrm called with unknown argument '$1'"
+		exit 1
 	;;
 esac
 
